### ISSUE TITLE
Replacement Lab

### ISSUE THREAD

**Issue by seancurran157** [kebaldwi/DNAC-TEMPLATES#263]
Hello, you provided a link in your README to a lab that has either been renamed or is no longer available. Can you suggest an alternative lab we can use instead?

link: https://dcloud2-sjc.cisco.com/content/catalogue?search=Enterprise%20Networks%20Hardware%20Sandbox&screenCommand=openFilterScreen

**Comment by kebaldwi** [comment]
Yes that works...
