### ISSUE TITLE
Issue with DNA deploying template config to switch interface

### ISSUE THREAD

**Issue by planter007** [kebaldwi/DNAC-TEMPLATES#4]
Hello,

Please see the error on the failed template deployment.  Thoughts?
![DNA error](https://user-images.githubusercontent.com/105950423/171434069-8d0c4a30-71e1-45bd-9caa-970980d3af76.PNG)

**Comment by kebaldwi** [comment]
Email sent - please read, and set up some time to meet and discuss what you are trying to do live.
