### ISSUE TITLE
Port assignments fail with composite template Platinum-PortAssign-Template.j2

### ISSUE THREAD

**Issue by jornlux** [kebaldwi/DNAC-TEMPLATES#6]
Hi.

Platinum-PortAssign-Template.j2 fails while trying to enumerate ports per switch in a stack, DNAC 2.3.3.5 and 9200 switches.

A rewrite fixed it on my end, you might want to consider changing the code if you can reproduce the error.

From:
{% for Switch in range(StackMemberCount) -%}
  {% set Model = StackPIDs[Switch] -%}
  {% if '48' in Model -%}
    **{% set PortTotal = PortTotal.append(48) -%}**
  {% elif '24' in Model %}
    **{% set PortTotal = PortTotal.append(24) -%}**  
  {% endif -%}
{% endfor -%}

To:
{% for Switch in range(StackMemberCount) -%}
  {% set Model = StackPIDs[Switch] -%}
  {% if '48' in Model -%}
    **{% set PortTotal[Switch]= PortTotal.append(48) -%}**
  {% elif '24' in Model %}
    **{% set PortTotal[Switch]= PortTotal.append(24) -%}**  
  {% endif -%}
{% endfor -%}

Otherwise, outstanding work on both the guides and the code/templates. Highly appreciated!

**Comment by kebaldwi** [comment]
Yes in case you forked the repo earlier on this file, you may want to sync it ... This was discovered at mentioned on the community feed... I fixed it another way by reducing code, and changing the operators... check out the snippet below.

If you pulled this code from somewhere other than the DAYN text file though please let me know so I can fix it in the location you acquired it from...

{% for Switch in range(StackMemberCount) -%}
  {% set Model = StackPIDs[Switch] -%}
  {% if '48' in Model -%}
    {% do PortTotal.append(48) -%}
  {% elif '24' in Model %}
    {% do PortTotal.append(24) -%}  
  {% endif -%}
{% endfor -%}
!

**Comment by kebaldwi** [comment]
I believe the fix should appear, there were multiple instances of it in the repo...

**Comment by jornlux** [comment]
Probably pulled before the fix was commited. Thanks.
